[package]
name = "com_interface_attribute"
version = "0.1.0"
authors = ["adrianwithah <lim.weiheng.hadrian@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.5", features = ["full", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0.1"