[package]
name = "com"
version = "0.0.1"
authors = ["Microsoft Corp"]
edition = "2018"

[workspace]
members = [
    "examples/basic/client",
    "examples/basic/server",
    "examples/basic/interface",
]