[package]
name = "interface"
version = "0.1.0"
authors = ["Microsoft Corp"]
edition = "2018"

[dependencies]
com = { path = "../../.." }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser", "winreg", "winerror", "winnt"] }

[lib]
crate-type = ["rlib", "cdylib"]