[package]
name = "macros"
version = "0.1.0"
authors = ["adrianwithah <lim.weiheng.hadrian@gmail.com>"]
edition = "2018"
autotests = false

[lib]
proc-macro = true

[[test]]
name = "tests"
path = "tests/progress.rs"

[dev-dependencies]
trybuild = "1.0.13"
com = { path = ".." }

[dependencies]
syn = { version = "1.0.5", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0.1"
com_interface_attribute = { path = "com_interface_attribute" }
co_class = { path = "co_class" }
aggr_co_class = { path = "aggr_co_class" }